package prototype1;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import prototype1.domain.Action;
import prototype1.domain.Condition;
import prototype1.domain.Decision;
import prototype1.domain.File;
import prototype1.domain.Project;
import prototype1.domain.Property;
import prototype1.domain.Target;
import prototype1.domain.Task;

public class MainMenu {
	
	public static Project createProject() {
		
		List<Target> targetList = new ArrayList<>();
		List<Task> taskList = new ArrayList<>();
		String name0 = "Classes";
		File input0 = new File("BuildClasses.java");
		File output0 = new File("BuildClasses.o");
		List<Property> propertyList0 = new ArrayList<>();
		List<Action> actionList0 = new ArrayList<>();
		Property propertyClasses0 = new Property("Build","build");
		propertyList0.add(propertyClasses0);
		Task task0 = new Task("BuildClasses","This java class is responsible of building other classes",propertyList0,actionList0,null);
		Target target0 = new Target(name0,input0,output0,task0,null);
		targetList.add(target0);
		String name1 = "Create";
		File input1 = new File("CreateAJar.java");
		File output1 = new File("CreateAJar.java");
		List<Property> propertyList1 = new ArrayList<>();
		List<Action> actionList1 = new ArrayList<>();
		Property propertyCreate0 = new Property("Dist","Dist");
		propertyList1.add(propertyCreate0);
		Task task1 = new Task("CreateJars","This java class is responsible for the creation of jar files.",propertyList1,actionList1,null);
		Target target1 = new Target(name1,input1,output1,task1,null);
		targetList.add(target1);
		String name2 = "NExplicit";
		File input2 = new File("CreatedJar.jar");
		File output2 = new File("CreatedJar.jar");
		List<Property> propertyList2 = new ArrayList<>();
		List<Action> actionList2 = new ArrayList<>();
		Property propertyNExplicit0 = new Property("Src","src");
		propertyList2.add(propertyNExplicit0);
		Task task2 = new Task("NonExplicit","2 java classes on this builder depend on this jar file.",propertyList2,actionList2,null);
		Target target2 = new Target(name2,input2,output2,task2,null);
		targetList.add(target2);
		List<Property> propertyTaskList0 = new ArrayList<>();
		List<Action> actionTaskList0 = new ArrayList<>();
		Property propertyDeleteFiles0 = new Property("Del","Del");
		propertyTaskList0.add(propertyDeleteFiles0);
		List<Decision> decisionTaskList0 = new ArrayList<>();
		List<Property> propertyTaskListDecision0 = new ArrayList<>();
		Property propertyTaskDecision0 = new Property("DeleteAlljar","boolean");
		propertyTaskListDecision0.add(propertyTaskDecision0);
		List<Condition> conditionTaskListDecision0 = new ArrayList<>();
		Condition conditionTaskDecision0 = new Condition("deletingFiles");
		conditionTaskListDecision0.add(conditionTaskDecision0);
		Condition conditionTaskDecision1 = new Condition("cleanBuild");
		conditionTaskListDecision0.add(conditionTaskDecision1);
		Decision decisionTask0 = new Decision(propertyTaskListDecision0,conditionTaskListDecision0);
		decisionTaskList0.add(decisionTask0);
		Action actionTask0 = new Action("DeleteJarFiles",decisionTaskList0);
		actionTaskList0.add(actionTask0);
		Task taskTask0 = new Task("DeleteFiles","Task to delete the temporary files generated by the build.",propertyTaskList0,actionTaskList0,null);
		taskList.add(taskTask0);
		Project project = new Project("JavaBuilder","v.1.30.2",targetList,taskList);
		return project;
	}
		
	public static void executeMenu(Project project) {
		
		boolean exit = false;
		Scanner input = new Scanner(System.in);
		
		while (!exit) {

			System.out.println(" # JavaBuilder ");
			System.out.println(" Please select one option:");
					
			System.out.println("0 - Exit");
			System.out.println("1 - Execute Tasks");
					
			String line = input.nextLine();
			int num = Integer.valueOf(line);
					
			switch (num) {
				case 0:
					exit = true;
					break;
				case 1:
					TaskMenu.executeMenu(project);
			}
		}
	}
}
