/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.Project2RuntimeModule;
import org.xtext.Project2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Project2IdeSetup extends Project2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Project2RuntimeModule(), new Project2IdeModule()));
	}
	
}
