/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import pt.isep.edom.assignment1.Assignment1Package;
import pt.isep.edom.assignment1.ClosureBackedAction;
import pt.isep.edom.assignment1.Condition;
import pt.isep.edom.assignment1.CustomAction;
import pt.isep.edom.assignment1.Decision;
import pt.isep.edom.assignment1.DefaultAction;
import pt.isep.edom.assignment1.End;
import pt.isep.edom.assignment1.File;
import pt.isep.edom.assignment1.IfDecision;
import pt.isep.edom.assignment1.Instruction;
import pt.isep.edom.assignment1.InstructionBlock;
import pt.isep.edom.assignment1.LoopDecision;
import pt.isep.edom.assignment1.Model;
import pt.isep.edom.assignment1.Project;
import pt.isep.edom.assignment1.Property;
import pt.isep.edom.assignment1.Start;
import pt.isep.edom.assignment1.Target;
import pt.isep.edom.assignment1.Task;
import pt.isep.edom.assignment1.WhileDecision;
import pt.isep.edom.xtext.assignment1.services.DslGrammarAccess;

@SuppressWarnings("all")
public class DslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == Assignment1Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case Assignment1Package.ACTION:
				sequence_Action_Impl(context, (pt.isep.edom.assignment1.Action) semanticObject); 
				return; 
			case Assignment1Package.CLOSURE_BACKED_ACTION:
				sequence_ClosureBackedAction(context, (ClosureBackedAction) semanticObject); 
				return; 
			case Assignment1Package.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case Assignment1Package.CUSTOM_ACTION:
				sequence_CustomAction(context, (CustomAction) semanticObject); 
				return; 
			case Assignment1Package.DECISION:
				sequence_Decision_Impl(context, (Decision) semanticObject); 
				return; 
			case Assignment1Package.DEFAULT_ACTION:
				sequence_DefaultAction(context, (DefaultAction) semanticObject); 
				return; 
			case Assignment1Package.END:
				sequence_End(context, (End) semanticObject); 
				return; 
			case Assignment1Package.FILE:
				sequence_File(context, (File) semanticObject); 
				return; 
			case Assignment1Package.IF_DECISION:
				sequence_IfDecision(context, (IfDecision) semanticObject); 
				return; 
			case Assignment1Package.INSTRUCTION:
				sequence_Instruction(context, (Instruction) semanticObject); 
				return; 
			case Assignment1Package.INSTRUCTION_BLOCK:
				sequence_InstructionBlock(context, (InstructionBlock) semanticObject); 
				return; 
			case Assignment1Package.LOOP_DECISION:
				sequence_LoopDecision_Impl(context, (LoopDecision) semanticObject); 
				return; 
			case Assignment1Package.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case Assignment1Package.PROJECT:
				sequence_Project(context, (Project) semanticObject); 
				return; 
			case Assignment1Package.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case Assignment1Package.START:
				sequence_Start(context, (Start) semanticObject); 
				return; 
			case Assignment1Package.TARGET:
				sequence_Target(context, (Target) semanticObject); 
				return; 
			case Assignment1Package.TASK:
				sequence_Task(context, (Task) semanticObject); 
				return; 
			case Assignment1Package.WHILE_DECISION:
				sequence_WhileDecision(context, (WhileDecision) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns Action
	 *     Action_Impl returns Action
	 *
	 * Constraint:
	 *     (name=EString (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_Action_Impl(ISerializationContext context, pt.isep.edom.assignment1.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns ClosureBackedAction
	 *     ClosureBackedAction returns ClosureBackedAction
	 *
	 * Constraint:
	 *     (name=EString (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_ClosureBackedAction(ISerializationContext context, ClosureBackedAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns Condition
	 *
	 * Constraint:
	 *     (stop_condition+=WhileDecision stop_condition+=WhileDecision*)?
	 * </pre>
	 */
	protected void sequence_Condition(ISerializationContext context, Condition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns CustomAction
	 *     CustomAction returns CustomAction
	 *
	 * Constraint:
	 *     (name=EString (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_CustomAction(ISerializationContext context, CustomAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Decision returns Decision
	 *     Decision_Impl returns Decision
	 *
	 * Constraint:
	 *     (has+=Property has+=Property*)?
	 * </pre>
	 */
	protected void sequence_Decision_Impl(ISerializationContext context, Decision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns DefaultAction
	 *     DefaultAction returns DefaultAction
	 *
	 * Constraint:
	 *     (name=EString (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_DefaultAction(ISerializationContext context, DefaultAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns End
	 *     End returns End
	 *
	 * Constraint:
	 *     (name=EString (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_End(ISerializationContext context, End semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     File returns File
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_File(ISerializationContext context, File semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Assignment1Package.Literals.FILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Assignment1Package.Literals.FILE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFileAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Decision returns IfDecision
	 *     IfDecision returns IfDecision
	 *
	 * Constraint:
	 *     (elseif+=[IfDecision|EString] elseif+=[IfDecision|EString]* (has+=Property has+=Property*)? contains+=Condition contains+=Condition*)
	 * </pre>
	 */
	protected void sequence_IfDecision(ISerializationContext context, IfDecision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InstructionBlock returns InstructionBlock
	 *
	 * Constraint:
	 *     (has+=Instruction has+=Instruction*)
	 * </pre>
	 */
	protected void sequence_InstructionBlock(ISerializationContext context, InstructionBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Instruction
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Instruction(ISerializationContext context, Instruction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Assignment1Package.Literals.INSTRUCTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Assignment1Package.Literals.INSTRUCTION__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInstructionAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Decision returns LoopDecision
	 *     LoopDecision_Impl returns LoopDecision
	 *
	 * Constraint:
	 *     (has+=Property has+=Property*)?
	 * </pre>
	 */
	protected void sequence_LoopDecision_Impl(ISerializationContext context, LoopDecision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=EString project=Project)
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Assignment1Package.Literals.MODEL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Assignment1Package.Literals.MODEL__NAME));
			if (transientValues.isValueTransient(semanticObject, Assignment1Package.Literals.MODEL__PROJECT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Assignment1Package.Literals.MODEL__PROJECT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getModelAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getModelAccess().getProjectProjectParserRuleCall_4_0(), semanticObject.getProject());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Project returns Project
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         version=EString? 
	 *         target+=Target 
	 *         target+=Target* 
	 *         tasks+=Task 
	 *         tasks+=Task*
	 *     )
	 * </pre>
	 */
	protected void sequence_Project(ISerializationContext context, Project semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (name=EString value=EString? (has+=[Property|EString] has+=[Property|EString]*)?)
	 * </pre>
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns Start
	 *     Start returns Start
	 *
	 * Constraint:
	 *     (name=EString next=[Action|EString]? (has+=InstructionBlock has+=InstructionBlock*)? (decisions+=Decision decisions+=Decision*)?)
	 * </pre>
	 */
	protected void sequence_Start(ISerializationContext context, Start semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Target returns Target
	 *
	 * Constraint:
	 *     ((dependencies+=[Target|EString] dependencies+=[Target|EString]*)? has=Task output=File)
	 * </pre>
	 */
	protected void sequence_Target(ISerializationContext context, Target semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Task returns Task
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         (depends+=[Task|EString] depends+=[Task|EString]*)? 
	 *         has+=Property 
	 *         has+=Property* 
	 *         (actions+=Action actions+=Action*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Task(ISerializationContext context, Task semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Decision returns WhileDecision
	 *     WhileDecision returns WhileDecision
	 *
	 * Constraint:
	 *     (has+=Property has+=Property*)?
	 * </pre>
	 */
	protected void sequence_WhileDecision(ISerializationContext context, WhileDecision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
