/**
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.generator;

import com.google.common.collect.Iterators;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import pt.isep.edom.assignment1.Action;
import pt.isep.edom.assignment1.Decision;
import pt.isep.edom.assignment1.Model;
import pt.isep.edom.assignment1.Property;
import pt.isep.edom.assignment1.Target;
import pt.isep.edom.assignment1.Task;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DslGenerator extends AbstractGenerator {
  public String generatePumlTarget(final EList<Target> list) {
    String stringAux = "";
    for (final Target t : list) {
      String _stringAux = stringAux;
      String _replace = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Target_" + _replace);
      String _plus_1 = (_plus + " { \n } \n");
      String _plus_2 = (_plus_1 + "Project ->");
      String _plus_3 = (_plus_2 + "Target_");
      String _replace_1 = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_4 = (_plus_3 + _replace_1);
      String _plus_5 = (_plus_4 + "\n");
      String _plus_6 = (_plus_5 + "class File_");
      String _replace_2 = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_7 = (_plus_6 + _replace_2);
      String _plus_8 = (_plus_7 + " { \n");
      String _plus_9 = (_plus_8 + "name ");
      String _name = t.getOutput().getName();
      String _plus_10 = (_plus_9 + _name);
      String _plus_11 = (_plus_10 + "\n } \n");
      String _plus_12 = (_plus_11 + "Target_");
      String _replace_3 = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_13 = (_plus_12 + _replace_3);
      String _plus_14 = (_plus_13 + "-> ");
      String _plus_15 = (_plus_14 + "File_");
      String _replace_4 = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_16 = (_plus_15 + _replace_4);
      String _plus_17 = (_plus_16 + " \n");
      String _plus_18 = (_plus_17 + "class Task_");
      String _replace_5 = t.getHas().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_19 = (_plus_18 + _replace_5);
      String _plus_20 = (_plus_19 + " { \n");
      String _plus_21 = (_plus_20 + "name ");
      String _name_1 = t.getHas().getName();
      String _plus_22 = (_plus_21 + _name_1);
      String _plus_23 = (_plus_22 + "\n");
      String _plus_24 = (_plus_23 + "description ");
      String _description = t.getHas().getDescription();
      String _plus_25 = (_plus_24 + _description);
      String _plus_26 = (_plus_25 + "\n } \n");
      String _plus_27 = (_plus_26 + "Target_");
      String _replace_6 = t.getOutput().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_28 = (_plus_27 + _replace_6);
      String _plus_29 = (_plus_28 + "->");
      String _plus_30 = (_plus_29 + "Task_");
      String _replace_7 = t.getHas().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_31 = (_plus_30 + _replace_7);
      String _plus_32 = (_plus_31 + "\n");
      String _generatePumlProperty = this.generatePumlProperty(t);
      String _plus_33 = (_plus_32 + _generatePumlProperty);
      stringAux = (_stringAux + _plus_33);
    }
    return stringAux;
  }

  public String generatePumlProperty(final Target t) {
    String stringAux = "";
    EList<Property> _has = t.getHas().getHas();
    for (final Property p : _has) {
      String _stringAux = stringAux;
      String _replace = p.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Property_" + _replace);
      String _plus_1 = (_plus + " { \n");
      String _plus_2 = (_plus_1 + 
        "name ");
      String _name = p.getName();
      String _plus_3 = (_plus_2 + _name);
      String _plus_4 = (_plus_3 + "\n");
      String _plus_5 = (_plus_4 + 
        "value ");
      String _value = p.getValue();
      String _plus_6 = (_plus_5 + _value);
      String _plus_7 = (_plus_6 + "\n");
      String _plus_8 = (_plus_7 + 
        " } \n ");
      String _plus_9 = (_plus_8 + "Task_");
      String _replace_1 = t.getHas().getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_10 = (_plus_9 + _replace_1);
      String _plus_11 = (_plus_10 + "->");
      String _plus_12 = (_plus_11 + "Property_");
      String _replace_2 = p.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_13 = (_plus_12 + _replace_2);
      String _plus_14 = (_plus_13 + "\n");
      stringAux = (_stringAux + _plus_14);
    }
    return stringAux;
  }

  public String generatePumlTask(final EList<Task> list) {
    String stringAux = "";
    for (final Task t : list) {
      String _stringAux = stringAux;
      String _replace = t.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Task_" + _replace);
      String _plus_1 = (_plus + " { \n");
      String _plus_2 = (_plus_1 + "name ");
      String _name = t.getName();
      String _plus_3 = (_plus_2 + _name);
      String _plus_4 = (_plus_3 + "\n");
      String _plus_5 = (_plus_4 + "description ");
      String _description = t.getDescription();
      String _plus_6 = (_plus_5 + _description);
      String _plus_7 = (_plus_6 + "\n");
      String _plus_8 = (_plus_7 + " } \n ");
      String _plus_9 = (_plus_8 + "Project ->");
      String _plus_10 = (_plus_9 + "Task_");
      String _replace_1 = t.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_11 = (_plus_10 + _replace_1);
      String _plus_12 = (_plus_11 + "\n");
      String _generatePumlAction = this.generatePumlAction(t);
      String _plus_13 = (_plus_12 + _generatePumlAction);
      stringAux = (_stringAux + _plus_13);
    }
    return stringAux;
  }

  public String generatePumlAction(final Task t) {
    String stringAux = "";
    EList<Action> _actions = t.getActions();
    for (final Action a : _actions) {
      String _stringAux = stringAux;
      String _replace = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Action_" + _replace);
      String _plus_1 = (_plus + "{ \n");
      String _plus_2 = (_plus_1 + "name ");
      String _name = a.getName();
      String _plus_3 = (_plus_2 + _name);
      String _plus_4 = (_plus_3 + "\n");
      String _plus_5 = (_plus_4 + " } \n");
      String _plus_6 = (_plus_5 + "Task_");
      String _replace_1 = t.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_7 = (_plus_6 + _replace_1);
      String _plus_8 = (_plus_7 + " -> Action_");
      String _replace_2 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_9 = (_plus_8 + _replace_2);
      String _plus_10 = (_plus_9 + "\n");
      String _plus_11 = (_plus_10 + "class InstructionBlock_");
      String _replace_3 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_12 = (_plus_11 + _replace_3);
      String _plus_13 = (_plus_12 + " { \n } \n");
      String _plus_14 = (_plus_13 + "Action_");
      String _replace_4 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_15 = (_plus_14 + _replace_4);
      String _plus_16 = (_plus_15 + " -> InstructionBlock_");
      String _replace_5 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_17 = (_plus_16 + _replace_5);
      String _plus_18 = (_plus_17 + "\n");
      String _plus_19 = (_plus_18 + "class Start_");
      String _replace_6 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_20 = (_plus_19 + _replace_6);
      String _plus_21 = (_plus_20 + " { \n } \n");
      String _plus_22 = (_plus_21 + "Action_");
      String _replace_7 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_23 = (_plus_22 + _replace_7);
      String _plus_24 = (_plus_23 + " -> Start_");
      String _replace_8 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_25 = (_plus_24 + _replace_8);
      String _plus_26 = (_plus_25 + "\n");
      String _plus_27 = (_plus_26 + "class End_");
      String _replace_9 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_28 = (_plus_27 + _replace_9);
      String _plus_29 = (_plus_28 + " { \n } \n");
      String _plus_30 = (_plus_29 + "Action_");
      String _replace_10 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_31 = (_plus_30 + _replace_10);
      String _plus_32 = (_plus_31 + " -> End_");
      String _replace_11 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_33 = (_plus_32 + _replace_11);
      String _plus_34 = (_plus_33 + "\n");
      String _plus_35 = (_plus_34 + "class InstructionBlock_");
      String _replace_12 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_36 = (_plus_35 + _replace_12);
      String _plus_37 = (_plus_36 + " { \n } \n");
      String _plus_38 = (_plus_37 + "Action_");
      String _replace_13 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_39 = (_plus_38 + _replace_13);
      String _plus_40 = (_plus_39 + " -> Instruction_InstructionBlock_");
      String _replace_14 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_41 = (_plus_40 + _replace_14);
      String _plus_42 = (_plus_41 + "\n");
      String _generatePumlDecision = this.generatePumlDecision(a);
      String _plus_43 = (_plus_42 + _generatePumlDecision);
      stringAux = (_stringAux + _plus_43);
    }
    return stringAux;
  }

  public String generatePumlDecision(final Action a) {
    String stringAux = "";
    EList<Decision> _decisions = a.getDecisions();
    for (final Decision d : _decisions) {
      String _stringAux = stringAux;
      String _replace = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Decision_" + _replace);
      String _plus_1 = (_plus + " { \n } \n");
      String _plus_2 = (_plus_1 + "Action_");
      String _replace_1 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_3 = (_plus_2 + _replace_1);
      String _plus_4 = (_plus_3 + " -> Decision_");
      String _replace_2 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_5 = (_plus_4 + _replace_2);
      String _plus_6 = (_plus_5 + "\n");
      String _generatePumlPropertyDecision = this.generatePumlPropertyDecision(a, d);
      String _plus_7 = (_plus_6 + _generatePumlPropertyDecision);
      stringAux = (_stringAux + _plus_7);
    }
    return stringAux;
  }

  public String generatePumlPropertyDecision(final Action a, final Decision d) {
    String stringAux = "";
    EList<Property> _has = d.getHas();
    for (final Property p : _has) {
      String _stringAux = stringAux;
      String _replace = p.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus = ("class Property_" + _replace);
      String _plus_1 = (_plus + " { \n } \n");
      String _plus_2 = (_plus_1 + "name ");
      String _name = p.getName();
      String _plus_3 = (_plus_2 + _name);
      String _plus_4 = (_plus_3 + "\n");
      String _plus_5 = (_plus_4 + "description ");
      String _value = p.getValue();
      String _plus_6 = (_plus_5 + _value);
      String _plus_7 = (_plus_6 + "\n } \n");
      String _plus_8 = (_plus_7 + "Decision_");
      String _replace_1 = a.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_9 = (_plus_8 + _replace_1);
      String _plus_10 = (_plus_9 + " -> Property_");
      String _replace_2 = p.getName().replaceAll(" ", "_").replace(".", "_");
      String _plus_11 = (_plus_10 + _replace_2);
      String _plus_12 = (_plus_11 + "\n");
      stringAux = (_stringAux + _plus_12);
    }
    return stringAux;
  }

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    String stringFormat = "@startuml \n";
    Model model = Iterators.<Model>filter(resource.getAllContents(), Model.class).next();
    String _stringFormat = stringFormat;
    String _name = model.getProject().getName();
    String _plus = ((("class Model { \nname \n" + "} ") + "class Project { \n name ") + _name);
    String _plus_1 = (_plus + "\n version \n");
    String _version = model.getProject().getVersion();
    String _plus_2 = (_plus_1 + _version);
    String _plus_3 = (_plus_2 + "} \n");
    String _plus_4 = (_plus_3 + "Model -> Project \n");
    String _generatePumlTarget = this.generatePumlTarget(model.getProject().getTarget());
    String _plus_5 = (_plus_4 + _generatePumlTarget);
    String _generatePumlTask = this.generatePumlTask(model.getProject().getTasks());
    String _plus_6 = (_plus_5 + _generatePumlTask);
    String _plus_7 = (_plus_6 + "@enduml \n");
    stringFormat = (_stringFormat + _plus_7);
    fsa.generateFile("xtext.puml", stringFormat);
  }
}
