/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import pt.isep.edom.xtext.assignment1.ui.internal.Assignment1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Assignment1Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Assignment1Activator activator = Assignment1Activator.getInstance();
		return activator != null ? activator.getInjector(Assignment1Activator.PT_ISEP_EDOM_XTEXT_ASSIGNMENT1_DSL) : null;
	}

}
