/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pt/isep/edom/xtext/assignment1/parser/antlr/internal/InternalDsl.tokens");
	}
}
