/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.edom.xtext.assignment1.ide.contentassist.antlr.internal.InternalDslParser;
import pt.isep.edom.xtext.assignment1.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getDecisionAccess().getAlternatives(), "rule__Decision__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_3(), "rule__Project__Group_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_7(), "rule__Project__Group_7__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_12(), "rule__Project__Group_12__0");
			builder.put(grammarAccess.getTargetAccess().getGroup(), "rule__Target__Group__0");
			builder.put(grammarAccess.getTargetAccess().getGroup_2(), "rule__Target__Group_2__0");
			builder.put(grammarAccess.getTargetAccess().getGroup_2_3(), "rule__Target__Group_2_3__0");
			builder.put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_3(), "rule__Task__Group_3__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_4(), "rule__Task__Group_4__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_4_3(), "rule__Task__Group_4_3__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_8(), "rule__Task__Group_8__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_10(), "rule__Task__Group_10__0");
			builder.put(grammarAccess.getTaskAccess().getGroup_10_3(), "rule__Task__Group_10_3__0");
			builder.put(grammarAccess.getFileAccess().getGroup(), "rule__File__Group__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_4(), "rule__Property__Group_4__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_5(), "rule__Property__Group_5__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_5_3(), "rule__Property__Group_5_3__0");
			builder.put(grammarAccess.getAction_ImplAccess().getGroup(), "rule__Action_Impl__Group__0");
			builder.put(grammarAccess.getAction_ImplAccess().getGroup_4(), "rule__Action_Impl__Group_4__0");
			builder.put(grammarAccess.getAction_ImplAccess().getGroup_4_3(), "rule__Action_Impl__Group_4_3__0");
			builder.put(grammarAccess.getAction_ImplAccess().getGroup_5(), "rule__Action_Impl__Group_5__0");
			builder.put(grammarAccess.getAction_ImplAccess().getGroup_5_3(), "rule__Action_Impl__Group_5_3__0");
			builder.put(grammarAccess.getInstructionBlockAccess().getGroup(), "rule__InstructionBlock__Group__0");
			builder.put(grammarAccess.getInstructionBlockAccess().getGroup_5(), "rule__InstructionBlock__Group_5__0");
			builder.put(grammarAccess.getDecision_ImplAccess().getGroup(), "rule__Decision_Impl__Group__0");
			builder.put(grammarAccess.getDecision_ImplAccess().getGroup_3(), "rule__Decision_Impl__Group_3__0");
			builder.put(grammarAccess.getDecision_ImplAccess().getGroup_3_3(), "rule__Decision_Impl__Group_3_3__0");
			builder.put(grammarAccess.getClosureBackedActionAccess().getGroup(), "rule__ClosureBackedAction__Group__0");
			builder.put(grammarAccess.getClosureBackedActionAccess().getGroup_4(), "rule__ClosureBackedAction__Group_4__0");
			builder.put(grammarAccess.getClosureBackedActionAccess().getGroup_4_3(), "rule__ClosureBackedAction__Group_4_3__0");
			builder.put(grammarAccess.getClosureBackedActionAccess().getGroup_5(), "rule__ClosureBackedAction__Group_5__0");
			builder.put(grammarAccess.getClosureBackedActionAccess().getGroup_5_3(), "rule__ClosureBackedAction__Group_5_3__0");
			builder.put(grammarAccess.getDefaultActionAccess().getGroup(), "rule__DefaultAction__Group__0");
			builder.put(grammarAccess.getDefaultActionAccess().getGroup_4(), "rule__DefaultAction__Group_4__0");
			builder.put(grammarAccess.getDefaultActionAccess().getGroup_4_3(), "rule__DefaultAction__Group_4_3__0");
			builder.put(grammarAccess.getDefaultActionAccess().getGroup_5(), "rule__DefaultAction__Group_5__0");
			builder.put(grammarAccess.getDefaultActionAccess().getGroup_5_3(), "rule__DefaultAction__Group_5_3__0");
			builder.put(grammarAccess.getCustomActionAccess().getGroup(), "rule__CustomAction__Group__0");
			builder.put(grammarAccess.getCustomActionAccess().getGroup_4(), "rule__CustomAction__Group_4__0");
			builder.put(grammarAccess.getCustomActionAccess().getGroup_4_3(), "rule__CustomAction__Group_4_3__0");
			builder.put(grammarAccess.getCustomActionAccess().getGroup_5(), "rule__CustomAction__Group_5__0");
			builder.put(grammarAccess.getCustomActionAccess().getGroup_5_3(), "rule__CustomAction__Group_5_3__0");
			builder.put(grammarAccess.getStartAccess().getGroup(), "rule__Start__Group__0");
			builder.put(grammarAccess.getStartAccess().getGroup_4(), "rule__Start__Group_4__0");
			builder.put(grammarAccess.getStartAccess().getGroup_5(), "rule__Start__Group_5__0");
			builder.put(grammarAccess.getStartAccess().getGroup_5_3(), "rule__Start__Group_5_3__0");
			builder.put(grammarAccess.getStartAccess().getGroup_6(), "rule__Start__Group_6__0");
			builder.put(grammarAccess.getStartAccess().getGroup_6_3(), "rule__Start__Group_6_3__0");
			builder.put(grammarAccess.getEndAccess().getGroup(), "rule__End__Group__0");
			builder.put(grammarAccess.getEndAccess().getGroup_4(), "rule__End__Group_4__0");
			builder.put(grammarAccess.getEndAccess().getGroup_4_3(), "rule__End__Group_4_3__0");
			builder.put(grammarAccess.getEndAccess().getGroup_5(), "rule__End__Group_5__0");
			builder.put(grammarAccess.getEndAccess().getGroup_5_3(), "rule__End__Group_5_3__0");
			builder.put(grammarAccess.getInstructionAccess().getGroup(), "rule__Instruction__Group__0");
			builder.put(grammarAccess.getIfDecisionAccess().getGroup(), "rule__IfDecision__Group__0");
			builder.put(grammarAccess.getIfDecisionAccess().getGroup_5(), "rule__IfDecision__Group_5__0");
			builder.put(grammarAccess.getIfDecisionAccess().getGroup_7(), "rule__IfDecision__Group_7__0");
			builder.put(grammarAccess.getIfDecisionAccess().getGroup_7_3(), "rule__IfDecision__Group_7_3__0");
			builder.put(grammarAccess.getIfDecisionAccess().getGroup_11(), "rule__IfDecision__Group_11__0");
			builder.put(grammarAccess.getWhileDecisionAccess().getGroup(), "rule__WhileDecision__Group__0");
			builder.put(grammarAccess.getWhileDecisionAccess().getGroup_3(), "rule__WhileDecision__Group_3__0");
			builder.put(grammarAccess.getWhileDecisionAccess().getGroup_3_3(), "rule__WhileDecision__Group_3_3__0");
			builder.put(grammarAccess.getLoopDecision_ImplAccess().getGroup(), "rule__LoopDecision_Impl__Group__0");
			builder.put(grammarAccess.getLoopDecision_ImplAccess().getGroup_3(), "rule__LoopDecision_Impl__Group_3__0");
			builder.put(grammarAccess.getLoopDecision_ImplAccess().getGroup_3_3(), "rule__LoopDecision_Impl__Group_3_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_3(), "rule__Condition__Group_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_3_3(), "rule__Condition__Group_3_3__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getProjectAssignment_4(), "rule__Model__ProjectAssignment_4");
			builder.put(grammarAccess.getProjectAccess().getNameAssignment_1(), "rule__Project__NameAssignment_1");
			builder.put(grammarAccess.getProjectAccess().getVersionAssignment_3_1(), "rule__Project__VersionAssignment_3_1");
			builder.put(grammarAccess.getProjectAccess().getTargetAssignment_6(), "rule__Project__TargetAssignment_6");
			builder.put(grammarAccess.getProjectAccess().getTargetAssignment_7_1(), "rule__Project__TargetAssignment_7_1");
			builder.put(grammarAccess.getProjectAccess().getTasksAssignment_11(), "rule__Project__TasksAssignment_11");
			builder.put(grammarAccess.getProjectAccess().getTasksAssignment_12_1(), "rule__Project__TasksAssignment_12_1");
			builder.put(grammarAccess.getTargetAccess().getDependenciesAssignment_2_2(), "rule__Target__DependenciesAssignment_2_2");
			builder.put(grammarAccess.getTargetAccess().getDependenciesAssignment_2_3_1(), "rule__Target__DependenciesAssignment_2_3_1");
			builder.put(grammarAccess.getTargetAccess().getHasAssignment_4(), "rule__Target__HasAssignment_4");
			builder.put(grammarAccess.getTargetAccess().getOutputAssignment_6(), "rule__Target__OutputAssignment_6");
			builder.put(grammarAccess.getTaskAccess().getNameAssignment_1(), "rule__Task__NameAssignment_1");
			builder.put(grammarAccess.getTaskAccess().getDescriptionAssignment_3_1(), "rule__Task__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getTaskAccess().getDependsAssignment_4_2(), "rule__Task__DependsAssignment_4_2");
			builder.put(grammarAccess.getTaskAccess().getDependsAssignment_4_3_1(), "rule__Task__DependsAssignment_4_3_1");
			builder.put(grammarAccess.getTaskAccess().getHasAssignment_7(), "rule__Task__HasAssignment_7");
			builder.put(grammarAccess.getTaskAccess().getHasAssignment_8_1(), "rule__Task__HasAssignment_8_1");
			builder.put(grammarAccess.getTaskAccess().getActionsAssignment_10_2(), "rule__Task__ActionsAssignment_10_2");
			builder.put(grammarAccess.getTaskAccess().getActionsAssignment_10_3_1(), "rule__Task__ActionsAssignment_10_3_1");
			builder.put(grammarAccess.getFileAccess().getNameAssignment_2(), "rule__File__NameAssignment_2");
			builder.put(grammarAccess.getPropertyAccess().getNameAssignment_2(), "rule__Property__NameAssignment_2");
			builder.put(grammarAccess.getPropertyAccess().getValueAssignment_4_1(), "rule__Property__ValueAssignment_4_1");
			builder.put(grammarAccess.getPropertyAccess().getHasAssignment_5_2(), "rule__Property__HasAssignment_5_2");
			builder.put(grammarAccess.getPropertyAccess().getHasAssignment_5_3_1(), "rule__Property__HasAssignment_5_3_1");
			builder.put(grammarAccess.getAction_ImplAccess().getNameAssignment_2(), "rule__Action_Impl__NameAssignment_2");
			builder.put(grammarAccess.getAction_ImplAccess().getHasAssignment_4_2(), "rule__Action_Impl__HasAssignment_4_2");
			builder.put(grammarAccess.getAction_ImplAccess().getHasAssignment_4_3_1(), "rule__Action_Impl__HasAssignment_4_3_1");
			builder.put(grammarAccess.getAction_ImplAccess().getDecisionsAssignment_5_2(), "rule__Action_Impl__DecisionsAssignment_5_2");
			builder.put(grammarAccess.getAction_ImplAccess().getDecisionsAssignment_5_3_1(), "rule__Action_Impl__DecisionsAssignment_5_3_1");
			builder.put(grammarAccess.getInstructionBlockAccess().getHasAssignment_4(), "rule__InstructionBlock__HasAssignment_4");
			builder.put(grammarAccess.getInstructionBlockAccess().getHasAssignment_5_1(), "rule__InstructionBlock__HasAssignment_5_1");
			builder.put(grammarAccess.getDecision_ImplAccess().getHasAssignment_3_2(), "rule__Decision_Impl__HasAssignment_3_2");
			builder.put(grammarAccess.getDecision_ImplAccess().getHasAssignment_3_3_1(), "rule__Decision_Impl__HasAssignment_3_3_1");
			builder.put(grammarAccess.getClosureBackedActionAccess().getNameAssignment_2(), "rule__ClosureBackedAction__NameAssignment_2");
			builder.put(grammarAccess.getClosureBackedActionAccess().getHasAssignment_4_2(), "rule__ClosureBackedAction__HasAssignment_4_2");
			builder.put(grammarAccess.getClosureBackedActionAccess().getHasAssignment_4_3_1(), "rule__ClosureBackedAction__HasAssignment_4_3_1");
			builder.put(grammarAccess.getClosureBackedActionAccess().getDecisionsAssignment_5_2(), "rule__ClosureBackedAction__DecisionsAssignment_5_2");
			builder.put(grammarAccess.getClosureBackedActionAccess().getDecisionsAssignment_5_3_1(), "rule__ClosureBackedAction__DecisionsAssignment_5_3_1");
			builder.put(grammarAccess.getDefaultActionAccess().getNameAssignment_2(), "rule__DefaultAction__NameAssignment_2");
			builder.put(grammarAccess.getDefaultActionAccess().getHasAssignment_4_2(), "rule__DefaultAction__HasAssignment_4_2");
			builder.put(grammarAccess.getDefaultActionAccess().getHasAssignment_4_3_1(), "rule__DefaultAction__HasAssignment_4_3_1");
			builder.put(grammarAccess.getDefaultActionAccess().getDecisionsAssignment_5_2(), "rule__DefaultAction__DecisionsAssignment_5_2");
			builder.put(grammarAccess.getDefaultActionAccess().getDecisionsAssignment_5_3_1(), "rule__DefaultAction__DecisionsAssignment_5_3_1");
			builder.put(grammarAccess.getCustomActionAccess().getNameAssignment_2(), "rule__CustomAction__NameAssignment_2");
			builder.put(grammarAccess.getCustomActionAccess().getHasAssignment_4_2(), "rule__CustomAction__HasAssignment_4_2");
			builder.put(grammarAccess.getCustomActionAccess().getHasAssignment_4_3_1(), "rule__CustomAction__HasAssignment_4_3_1");
			builder.put(grammarAccess.getCustomActionAccess().getDecisionsAssignment_5_2(), "rule__CustomAction__DecisionsAssignment_5_2");
			builder.put(grammarAccess.getCustomActionAccess().getDecisionsAssignment_5_3_1(), "rule__CustomAction__DecisionsAssignment_5_3_1");
			builder.put(grammarAccess.getStartAccess().getNameAssignment_2(), "rule__Start__NameAssignment_2");
			builder.put(grammarAccess.getStartAccess().getNextAssignment_4_1(), "rule__Start__NextAssignment_4_1");
			builder.put(grammarAccess.getStartAccess().getHasAssignment_5_2(), "rule__Start__HasAssignment_5_2");
			builder.put(grammarAccess.getStartAccess().getHasAssignment_5_3_1(), "rule__Start__HasAssignment_5_3_1");
			builder.put(grammarAccess.getStartAccess().getDecisionsAssignment_6_2(), "rule__Start__DecisionsAssignment_6_2");
			builder.put(grammarAccess.getStartAccess().getDecisionsAssignment_6_3_1(), "rule__Start__DecisionsAssignment_6_3_1");
			builder.put(grammarAccess.getEndAccess().getNameAssignment_2(), "rule__End__NameAssignment_2");
			builder.put(grammarAccess.getEndAccess().getHasAssignment_4_2(), "rule__End__HasAssignment_4_2");
			builder.put(grammarAccess.getEndAccess().getHasAssignment_4_3_1(), "rule__End__HasAssignment_4_3_1");
			builder.put(grammarAccess.getEndAccess().getDecisionsAssignment_5_2(), "rule__End__DecisionsAssignment_5_2");
			builder.put(grammarAccess.getEndAccess().getDecisionsAssignment_5_3_1(), "rule__End__DecisionsAssignment_5_3_1");
			builder.put(grammarAccess.getInstructionAccess().getNameAssignment_2(), "rule__Instruction__NameAssignment_2");
			builder.put(grammarAccess.getIfDecisionAccess().getElseifAssignment_4(), "rule__IfDecision__ElseifAssignment_4");
			builder.put(grammarAccess.getIfDecisionAccess().getElseifAssignment_5_1(), "rule__IfDecision__ElseifAssignment_5_1");
			builder.put(grammarAccess.getIfDecisionAccess().getHasAssignment_7_2(), "rule__IfDecision__HasAssignment_7_2");
			builder.put(grammarAccess.getIfDecisionAccess().getHasAssignment_7_3_1(), "rule__IfDecision__HasAssignment_7_3_1");
			builder.put(grammarAccess.getIfDecisionAccess().getContainsAssignment_10(), "rule__IfDecision__ContainsAssignment_10");
			builder.put(grammarAccess.getIfDecisionAccess().getContainsAssignment_11_1(), "rule__IfDecision__ContainsAssignment_11_1");
			builder.put(grammarAccess.getWhileDecisionAccess().getHasAssignment_3_2(), "rule__WhileDecision__HasAssignment_3_2");
			builder.put(grammarAccess.getWhileDecisionAccess().getHasAssignment_3_3_1(), "rule__WhileDecision__HasAssignment_3_3_1");
			builder.put(grammarAccess.getLoopDecision_ImplAccess().getHasAssignment_3_2(), "rule__LoopDecision_Impl__HasAssignment_3_2");
			builder.put(grammarAccess.getLoopDecision_ImplAccess().getHasAssignment_3_3_1(), "rule__LoopDecision_Impl__HasAssignment_3_3_1");
			builder.put(grammarAccess.getConditionAccess().getStop_conditionAssignment_3_2(), "rule__Condition__Stop_conditionAssignment_3_2");
			builder.put(grammarAccess.getConditionAccess().getStop_conditionAssignment_3_3_1(), "rule__Condition__Stop_conditionAssignment_3_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
