/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.p2.ui.internal.P2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Project2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(P2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		P2Activator activator = P2Activator.getInstance();
		return activator != null ? activator.getInjector(P2Activator.ORG_XTEXT_PROJECT2) : null;
	}

}
