/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pt.isep.edom.xtext.assignment1.ui.internal.Assignment1Activator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment1Activator.getInstance().getInjector("pt.isep.edom.xtext.assignment1.Dsl");
	}

}
