/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
