/*
 * generated by Xtext 2.25.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class Project2GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cProjectKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cProjectAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cProjectProjectParserRuleCall_4_0 = (RuleCall)cProjectAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Model returns Model:
		//    'Model'
		//    name=EString
		//    '{'
		//        'project' project=Project
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Model'
		//name=EString
		//'{'
		//    'project' project=Project
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Model'
		public Keyword getModelKeyword_0() { return cModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'project'
		public Keyword getProjectKeyword_3() { return cProjectKeyword_3; }
		
		//project=Project
		public Assignment getProjectAssignment_4() { return cProjectAssignment_4; }
		
		//Project
		public RuleCall getProjectProjectParserRuleCall_4_0() { return cProjectProjectParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAction_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInstructionBlockParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStartParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEndParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Action returns Action:
		//    Action_Impl | InstructionBlock | Start | End;
		@Override public ParserRule getRule() { return rule; }
		
		//Action_Impl | InstructionBlock | Start | End
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Action_Impl
		public RuleCall getAction_ImplParserRuleCall_0() { return cAction_ImplParserRuleCall_0; }
		
		//InstructionBlock
		public RuleCall getInstructionBlockParserRuleCall_1() { return cInstructionBlockParserRuleCall_1; }
		
		//Start
		public RuleCall getStartParserRuleCall_2() { return cStartParserRuleCall_2; }
		
		//End
		public RuleCall getEndParserRuleCall_3() { return cEndParserRuleCall_3; }
	}
	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProjectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVersionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cVersionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cVersionEStringParserRuleCall_3_1_0 = (RuleCall)cVersionAssignment_3_1.eContents().get(0);
		private final Keyword cTargetKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTargetAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTargetTargetParserRuleCall_6_0 = (RuleCall)cTargetAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTargetAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTargetTargetParserRuleCall_7_1_0 = (RuleCall)cTargetAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cTasksKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cTasksAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cTasksTaskParserRuleCall_11_0 = (RuleCall)cTasksAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cTasksAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cTasksTaskParserRuleCall_12_1_0 = (RuleCall)cTasksAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Project returns Project:
		//    'Project'
		//    name=EString
		//    '{'
		//        ('version' version=EString)?
		//        'target' '{' target+=Target ( "," target+=Target)* '}'
		//        'tasks' '{' tasks+=Task ( "," tasks+=Task)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Project'
		//name=EString
		//'{'
		//    ('version' version=EString)?
		//    'target' '{' target+=Target ( "," target+=Target)* '}'
		//    'tasks' '{' tasks+=Task ( "," tasks+=Task)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Project'
		public Keyword getProjectKeyword_0() { return cProjectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('version' version=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'version'
		public Keyword getVersionKeyword_3_0() { return cVersionKeyword_3_0; }
		
		//version=EString
		public Assignment getVersionAssignment_3_1() { return cVersionAssignment_3_1; }
		
		//EString
		public RuleCall getVersionEStringParserRuleCall_3_1_0() { return cVersionEStringParserRuleCall_3_1_0; }
		
		//'target'
		public Keyword getTargetKeyword_4() { return cTargetKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//target+=Target
		public Assignment getTargetAssignment_6() { return cTargetAssignment_6; }
		
		//Target
		public RuleCall getTargetTargetParserRuleCall_6_0() { return cTargetTargetParserRuleCall_6_0; }
		
		//( "," target+=Target)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//target+=Target
		public Assignment getTargetAssignment_7_1() { return cTargetAssignment_7_1; }
		
		//Target
		public RuleCall getTargetTargetParserRuleCall_7_1_0() { return cTargetTargetParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'tasks'
		public Keyword getTasksKeyword_9() { return cTasksKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//tasks+=Task
		public Assignment getTasksAssignment_11() { return cTasksAssignment_11; }
		
		//Task
		public RuleCall getTasksTaskParserRuleCall_11_0() { return cTasksTaskParserRuleCall_11_0; }
		
		//( "," tasks+=Task)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//tasks+=Task
		public Assignment getTasksAssignment_12_1() { return cTasksAssignment_12_1; }
		
		//Task
		public RuleCall getTasksTaskParserRuleCall_12_1_0() { return cTasksTaskParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class TargetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Target");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTargetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDependenciesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cDependenciesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cDependenciesTargetCrossReference_3_2_0 = (CrossReference)cDependenciesAssignment_3_2.eContents().get(0);
		private final RuleCall cDependenciesTargetEStringParserRuleCall_3_2_0_1 = (RuleCall)cDependenciesTargetCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cDependenciesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cDependenciesTargetCrossReference_3_3_1_0 = (CrossReference)cDependenciesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cDependenciesTargetEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cDependenciesTargetCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cHasKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cHasAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cHasTaskParserRuleCall_5_0 = (RuleCall)cHasAssignment_5.eContents().get(0);
		private final Keyword cOutputKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cOutputAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOutputFileParserRuleCall_7_0 = (RuleCall)cOutputAssignment_7.eContents().get(0);
		private final Keyword cInputKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cInputAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cInputFileParserRuleCall_9_0 = (RuleCall)cInputAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Target returns Target:
		//    'Target'
		//    name=EString
		//    '{'
		//        ('dependencies' '(' dependencies+=[Target|EString] ( "," dependencies+=[Target|EString])* ')' )?
		//        'has' has=Task
		//        'output' output=File
		//        'input' input=File
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Target'
		//name=EString
		//'{'
		//    ('dependencies' '(' dependencies+=[Target|EString] ( "," dependencies+=[Target|EString])* ')' )?
		//    'has' has=Task
		//    'output' output=File
		//    'input' input=File
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Target'
		public Keyword getTargetKeyword_0() { return cTargetKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('dependencies' '(' dependencies+=[Target|EString] ( "," dependencies+=[Target|EString])* ')' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'dependencies'
		public Keyword getDependenciesKeyword_3_0() { return cDependenciesKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//dependencies+=[Target|EString]
		public Assignment getDependenciesAssignment_3_2() { return cDependenciesAssignment_3_2; }
		
		//[Target|EString]
		public CrossReference getDependenciesTargetCrossReference_3_2_0() { return cDependenciesTargetCrossReference_3_2_0; }
		
		//EString
		public RuleCall getDependenciesTargetEStringParserRuleCall_3_2_0_1() { return cDependenciesTargetEStringParserRuleCall_3_2_0_1; }
		
		//( "," dependencies+=[Target|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//dependencies+=[Target|EString]
		public Assignment getDependenciesAssignment_3_3_1() { return cDependenciesAssignment_3_3_1; }
		
		//[Target|EString]
		public CrossReference getDependenciesTargetCrossReference_3_3_1_0() { return cDependenciesTargetCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getDependenciesTargetEStringParserRuleCall_3_3_1_0_1() { return cDependenciesTargetEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//'has'
		public Keyword getHasKeyword_4() { return cHasKeyword_4; }
		
		//has=Task
		public Assignment getHasAssignment_5() { return cHasAssignment_5; }
		
		//Task
		public RuleCall getHasTaskParserRuleCall_5_0() { return cHasTaskParserRuleCall_5_0; }
		
		//'output'
		public Keyword getOutputKeyword_6() { return cOutputKeyword_6; }
		
		//output=File
		public Assignment getOutputAssignment_7() { return cOutputAssignment_7; }
		
		//File
		public RuleCall getOutputFileParserRuleCall_7_0() { return cOutputFileParserRuleCall_7_0; }
		
		//'input'
		public Keyword getInputKeyword_8() { return cInputKeyword_8; }
		
		//input=File
		public Assignment getInputAssignment_9() { return cInputAssignment_9; }
		
		//File
		public RuleCall getInputFileParserRuleCall_9_0() { return cInputFileParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTaskAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTaskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDependsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDependsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDependsTaskCrossReference_5_2_0 = (CrossReference)cDependsAssignment_5_2.eContents().get(0);
		private final RuleCall cDependsTaskEStringParserRuleCall_5_2_0_1 = (RuleCall)cDependsTaskCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDependsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDependsTaskCrossReference_5_3_1_0 = (CrossReference)cDependsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDependsTaskEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDependsTaskCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cHasKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHasAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cHasPropertyParserRuleCall_6_2_0 = (RuleCall)cHasAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHasAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cHasPropertyParserRuleCall_6_3_1_0 = (RuleCall)cHasAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cActionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cActionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_7_2_0 = (RuleCall)cActionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cActionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_7_3_1_0 = (RuleCall)cActionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Task returns Task:
		//    {Task}
		//    'Task'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('depends' '(' depends+=[Task|EString] ( "," depends+=[Task|EString])* ')' )?
		//        ('has' '{' has+=Property ( "," has+=Property)* '}' )?
		//        ('actions' '{' actions+=Action ( "," actions+=Action)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Task}
		//'Task'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('depends' '(' depends+=[Task|EString] ( "," depends+=[Task|EString])* ')' )?
		//    ('has' '{' has+=Property ( "," has+=Property)* '}' )?
		//    ('actions' '{' actions+=Action ( "," actions+=Action)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Task}
		public Action getTaskAction_0() { return cTaskAction_0; }
		
		//'Task'
		public Keyword getTaskKeyword_1() { return cTaskKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('depends' '(' depends+=[Task|EString] ( "," depends+=[Task|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'depends'
		public Keyword getDependsKeyword_5_0() { return cDependsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//depends+=[Task|EString]
		public Assignment getDependsAssignment_5_2() { return cDependsAssignment_5_2; }
		
		//[Task|EString]
		public CrossReference getDependsTaskCrossReference_5_2_0() { return cDependsTaskCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDependsTaskEStringParserRuleCall_5_2_0_1() { return cDependsTaskEStringParserRuleCall_5_2_0_1; }
		
		//( "," depends+=[Task|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//depends+=[Task|EString]
		public Assignment getDependsAssignment_5_3_1() { return cDependsAssignment_5_3_1; }
		
		//[Task|EString]
		public CrossReference getDependsTaskCrossReference_5_3_1_0() { return cDependsTaskCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDependsTaskEStringParserRuleCall_5_3_1_0_1() { return cDependsTaskEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('has' '{' has+=Property ( "," has+=Property)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'has'
		public Keyword getHasKeyword_6_0() { return cHasKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//has+=Property
		public Assignment getHasAssignment_6_2() { return cHasAssignment_6_2; }
		
		//Property
		public RuleCall getHasPropertyParserRuleCall_6_2_0() { return cHasPropertyParserRuleCall_6_2_0; }
		
		//( "," has+=Property)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//has+=Property
		public Assignment getHasAssignment_6_3_1() { return cHasAssignment_6_3_1; }
		
		//Property
		public RuleCall getHasPropertyParserRuleCall_6_3_1_0() { return cHasPropertyParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('actions' '{' actions+=Action ( "," actions+=Action)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'actions'
		public Keyword getActionsKeyword_7_0() { return cActionsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//actions+=Action
		public Assignment getActionsAssignment_7_2() { return cActionsAssignment_7_2; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_7_2_0() { return cActionsActionParserRuleCall_7_2_0; }
		
		//( "," actions+=Action)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//actions+=Action
		public Assignment getActionsAssignment_7_3_1() { return cActionsAssignment_7_3_1; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_7_3_1_0() { return cActionsActionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.File");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFileAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFileKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//File returns File:
		//    {File}
		//    'File'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{File}
		//'File'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{File}
		public Action getFileAction_0() { return cFileAction_0; }
		
		//'File'
		public Keyword getFileKeyword_1() { return cFileKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPropertyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Property returns Property:
		//    {Property}
		//    'Property'
		//    name=EString
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Property}
		//'Property'
		//name=EString
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Property}
		public Action getPropertyAction_0() { return cPropertyAction_0; }
		
		//'Property'
		public Keyword getPropertyKeyword_1() { return cPropertyKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('value' value=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'value'
		public Keyword getValueKeyword_4_0() { return cValueKeyword_4_0; }
		
		//value=EString
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_4_1_0() { return cValueEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Action_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Action_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDecisionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDecisionsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDecisionsDecisionParserRuleCall_4_2_0 = (RuleCall)cDecisionsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDecisionsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDecisionsDecisionParserRuleCall_4_3_1_0 = (RuleCall)cDecisionsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Action_Impl returns Action:
		//    {Action}
		//    'Action'
		//    name=EString
		//    '{'
		//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Action}
		//'Action'
		//name=EString
		//'{'
		//    ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Action}
		public Action getActionAction_0() { return cActionAction_0; }
		
		//'Action'
		public Keyword getActionKeyword_1() { return cActionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'decisions'
		public Keyword getDecisionsKeyword_4_0() { return cDecisionsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_4_2() { return cDecisionsAssignment_4_2; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_4_2_0() { return cDecisionsDecisionParserRuleCall_4_2_0; }
		
		//( "," decisions+=Decision)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_4_3_1() { return cDecisionsAssignment_4_3_1; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_4_3_1_0() { return cDecisionsDecisionParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class DecisionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Decision");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDecisionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cHasKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cHasAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cHasPropertyParserRuleCall_2_2_0 = (RuleCall)cHasAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cHasAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cHasPropertyParserRuleCall_2_3_1_0 = (RuleCall)cHasAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cConditionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cConditionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConditionConditionParserRuleCall_5_0 = (RuleCall)cConditionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cConditionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cConditionConditionParserRuleCall_6_1_0 = (RuleCall)cConditionAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Decision returns Decision:
		//    'Decision'
		//    '{'
		//        ('has' '{' has+=Property ( "," has+=Property)* '}' )?
		//        'condition' '{' condition+=Condition ( "," condition+=Condition)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Decision'
		//'{'
		//    ('has' '{' has+=Property ( "," has+=Property)* '}' )?
		//    'condition' '{' condition+=Condition ( "," condition+=Condition)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Decision'
		public Keyword getDecisionKeyword_0() { return cDecisionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('has' '{' has+=Property ( "," has+=Property)* '}' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'has'
		public Keyword getHasKeyword_2_0() { return cHasKeyword_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }
		
		//has+=Property
		public Assignment getHasAssignment_2_2() { return cHasAssignment_2_2; }
		
		//Property
		public RuleCall getHasPropertyParserRuleCall_2_2_0() { return cHasPropertyParserRuleCall_2_2_0; }
		
		//( "," has+=Property)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//has+=Property
		public Assignment getHasAssignment_2_3_1() { return cHasAssignment_2_3_1; }
		
		//Property
		public RuleCall getHasPropertyParserRuleCall_2_3_1_0() { return cHasPropertyParserRuleCall_2_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
		
		//'condition'
		public Keyword getConditionKeyword_3() { return cConditionKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//condition+=Condition
		public Assignment getConditionAssignment_5() { return cConditionAssignment_5; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_5_0() { return cConditionConditionParserRuleCall_5_0; }
		
		//( "," condition+=Condition)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//condition+=Condition
		public Assignment getConditionAssignment_6_1() { return cConditionAssignment_6_1; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_6_1_0() { return cConditionConditionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class InstructionBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.InstructionBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInstructionBlockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDecisionsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cDecisionsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cDecisionsDecisionParserRuleCall_3_2_0 = (RuleCall)cDecisionsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cDecisionsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cDecisionsDecisionParserRuleCall_3_3_1_0 = (RuleCall)cDecisionsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cHasKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHasAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cHasInstructionParserRuleCall_6_0 = (RuleCall)cHasAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cHasAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cHasInstructionParserRuleCall_7_1_0 = (RuleCall)cHasAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//InstructionBlock returns InstructionBlock:
		//    'InstructionBlock'
		//    name=EString
		//    '{'
		//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//        'has' '{' has+=Instruction ( "," has+=Instruction)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'InstructionBlock'
		//name=EString
		//'{'
		//    ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//    'has' '{' has+=Instruction ( "," has+=Instruction)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'InstructionBlock'
		public Keyword getInstructionBlockKeyword_0() { return cInstructionBlockKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'decisions'
		public Keyword getDecisionsKeyword_3_0() { return cDecisionsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_3_2() { return cDecisionsAssignment_3_2; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_3_2_0() { return cDecisionsDecisionParserRuleCall_3_2_0; }
		
		//( "," decisions+=Decision)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_3_3_1() { return cDecisionsAssignment_3_3_1; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_3_3_1_0() { return cDecisionsDecisionParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'has'
		public Keyword getHasKeyword_4() { return cHasKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//has+=Instruction
		public Assignment getHasAssignment_6() { return cHasAssignment_6; }
		
		//Instruction
		public RuleCall getHasInstructionParserRuleCall_6_0() { return cHasInstructionParserRuleCall_6_0; }
		
		//( "," has+=Instruction)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//has+=Instruction
		public Assignment getHasAssignment_7_1() { return cHasAssignment_7_1; }
		
		//Instruction
		public RuleCall getHasInstructionParserRuleCall_7_1_0() { return cHasInstructionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class StartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Start");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStartAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStartKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cNextActionCrossReference_4_1_0 = (CrossReference)cNextAssignment_4_1.eContents().get(0);
		private final RuleCall cNextActionEStringParserRuleCall_4_1_0_1 = (RuleCall)cNextActionCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDecisionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDecisionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cDecisionsDecisionParserRuleCall_5_2_0 = (RuleCall)cDecisionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDecisionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cDecisionsDecisionParserRuleCall_5_3_1_0 = (RuleCall)cDecisionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Start returns Start:
		//    {Start}
		//    'Start'
		//    name=EString
		//    '{'
		//        ('next' next=[Action|EString])?
		//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Start}
		//'Start'
		//name=EString
		//'{'
		//    ('next' next=[Action|EString])?
		//    ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Start}
		public Action getStartAction_0() { return cStartAction_0; }
		
		//'Start'
		public Keyword getStartKeyword_1() { return cStartKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('next' next=[Action|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'next'
		public Keyword getNextKeyword_4_0() { return cNextKeyword_4_0; }
		
		//next=[Action|EString]
		public Assignment getNextAssignment_4_1() { return cNextAssignment_4_1; }
		
		//[Action|EString]
		public CrossReference getNextActionCrossReference_4_1_0() { return cNextActionCrossReference_4_1_0; }
		
		//EString
		public RuleCall getNextActionEStringParserRuleCall_4_1_0_1() { return cNextActionEStringParserRuleCall_4_1_0_1; }
		
		//('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'decisions'
		public Keyword getDecisionsKeyword_5_0() { return cDecisionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_5_2() { return cDecisionsAssignment_5_2; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_5_2_0() { return cDecisionsDecisionParserRuleCall_5_2_0; }
		
		//( "," decisions+=Decision)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_5_3_1() { return cDecisionsAssignment_5_3_1; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_5_3_1_0() { return cDecisionsDecisionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.End");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEndAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEndKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDecisionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDecisionsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDecisionsDecisionParserRuleCall_4_2_0 = (RuleCall)cDecisionsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDecisionsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDecisionsDecisionParserRuleCall_4_3_1_0 = (RuleCall)cDecisionsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//End returns End:
		//    {End}
		//    'End'
		//    name=EString
		//    '{'
		//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{End}
		//'End'
		//name=EString
		//'{'
		//    ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{End}
		public Action getEndAction_0() { return cEndAction_0; }
		
		//'End'
		public Keyword getEndKeyword_1() { return cEndKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'decisions'
		public Keyword getDecisionsKeyword_4_0() { return cDecisionsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_4_2() { return cDecisionsAssignment_4_2; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_4_2_0() { return cDecisionsDecisionParserRuleCall_4_2_0; }
		
		//( "," decisions+=Decision)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//decisions+=Decision
		public Assignment getDecisionsAssignment_4_3_1() { return cDecisionsAssignment_4_3_1; }
		
		//Decision
		public RuleCall getDecisionsDecisionParserRuleCall_4_3_1_0() { return cDecisionsDecisionParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConditionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConditionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Condition returns Condition:
		//    {Condition}
		//    'Condition'
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Condition}
		//'Condition'
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Condition}
		public Action getConditionAction_0() { return cConditionAction_0; }
		
		//'Condition'
		public Keyword getConditionKeyword_1() { return cConditionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Project2.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInstructionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInstructionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Instruction returns Instruction:
		//    {Instruction}
		//    'Instruction'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Instruction}
		//'Instruction'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Instruction}
		public Action getInstructionAction_0() { return cInstructionAction_0; }
		
		//'Instruction'
		public Keyword getInstructionKeyword_1() { return cInstructionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private final ModelElements pModel;
	private final ActionElements pAction;
	private final ProjectElements pProject;
	private final EStringElements pEString;
	private final TargetElements pTarget;
	private final TaskElements pTask;
	private final FileElements pFile;
	private final PropertyElements pProperty;
	private final Action_ImplElements pAction_Impl;
	private final DecisionElements pDecision;
	private final InstructionBlockElements pInstructionBlock;
	private final StartElements pStart;
	private final EndElements pEnd;
	private final ConditionElements pCondition;
	private final InstructionElements pInstruction;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public Project2GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAction = new ActionElements();
		this.pProject = new ProjectElements();
		this.pEString = new EStringElements();
		this.pTarget = new TargetElements();
		this.pTask = new TaskElements();
		this.pFile = new FileElements();
		this.pProperty = new PropertyElements();
		this.pAction_Impl = new Action_ImplElements();
		this.pDecision = new DecisionElements();
		this.pInstructionBlock = new InstructionBlockElements();
		this.pStart = new StartElements();
		this.pEnd = new EndElements();
		this.pCondition = new ConditionElements();
		this.pInstruction = new InstructionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Project2".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model returns Model:
	//    'Model'
	//    name=EString
	//    '{'
	//        'project' project=Project
	//    '}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Action returns Action:
	//    Action_Impl | InstructionBlock | Start | End;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Project returns Project:
	//    'Project'
	//    name=EString
	//    '{'
	//        ('version' version=EString)?
	//        'target' '{' target+=Target ( "," target+=Target)* '}'
	//        'tasks' '{' tasks+=Task ( "," tasks+=Task)* '}'
	//    '}';
	public ProjectElements getProjectAccess() {
		return pProject;
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Target returns Target:
	//    'Target'
	//    name=EString
	//    '{'
	//        ('dependencies' '(' dependencies+=[Target|EString] ( "," dependencies+=[Target|EString])* ')' )?
	//        'has' has=Task
	//        'output' output=File
	//        'input' input=File
	//    '}';
	public TargetElements getTargetAccess() {
		return pTarget;
	}
	
	public ParserRule getTargetRule() {
		return getTargetAccess().getRule();
	}
	
	//Task returns Task:
	//    {Task}
	//    'Task'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('depends' '(' depends+=[Task|EString] ( "," depends+=[Task|EString])* ')' )?
	//        ('has' '{' has+=Property ( "," has+=Property)* '}' )?
	//        ('actions' '{' actions+=Action ( "," actions+=Action)* '}' )?
	//    '}';
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//File returns File:
	//    {File}
	//    'File'
	//    name=EString;
	public FileElements getFileAccess() {
		return pFile;
	}
	
	public ParserRule getFileRule() {
		return getFileAccess().getRule();
	}
	
	//Property returns Property:
	//    {Property}
	//    'Property'
	//    name=EString
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}
	
	//Action_Impl returns Action:
	//    {Action}
	//    'Action'
	//    name=EString
	//    '{'
	//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
	//    '}';
	public Action_ImplElements getAction_ImplAccess() {
		return pAction_Impl;
	}
	
	public ParserRule getAction_ImplRule() {
		return getAction_ImplAccess().getRule();
	}
	
	//Decision returns Decision:
	//    'Decision'
	//    '{'
	//        ('has' '{' has+=Property ( "," has+=Property)* '}' )?
	//        'condition' '{' condition+=Condition ( "," condition+=Condition)* '}'
	//    '}';
	public DecisionElements getDecisionAccess() {
		return pDecision;
	}
	
	public ParserRule getDecisionRule() {
		return getDecisionAccess().getRule();
	}
	
	//InstructionBlock returns InstructionBlock:
	//    'InstructionBlock'
	//    name=EString
	//    '{'
	//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
	//        'has' '{' has+=Instruction ( "," has+=Instruction)* '}'
	//    '}';
	public InstructionBlockElements getInstructionBlockAccess() {
		return pInstructionBlock;
	}
	
	public ParserRule getInstructionBlockRule() {
		return getInstructionBlockAccess().getRule();
	}
	
	//Start returns Start:
	//    {Start}
	//    'Start'
	//    name=EString
	//    '{'
	//        ('next' next=[Action|EString])?
	//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
	//    '}';
	public StartElements getStartAccess() {
		return pStart;
	}
	
	public ParserRule getStartRule() {
		return getStartAccess().getRule();
	}
	
	//End returns End:
	//    {End}
	//    'End'
	//    name=EString
	//    '{'
	//        ('decisions' '{' decisions+=Decision ( "," decisions+=Decision)* '}' )?
	//    '}';
	public EndElements getEndAccess() {
		return pEnd;
	}
	
	public ParserRule getEndRule() {
		return getEndAccess().getRule();
	}
	
	//Condition returns Condition:
	//    {Condition}
	//    'Condition'
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Instruction returns Instruction:
	//    {Instruction}
	//    'Instruction'
	//    name=EString;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
