/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Project2UiModule extends AbstractProject2UiModule {

	public Project2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
