@startuml
left to right direction
class Model {
name ModelCBuilder
}
class Project {
name CBuilder
version v.22.30.2
}
Model -up-> Project
class Target_BuildClasses_c {
}
Project -down->Target_BuildClasses_c
class File_BuildClasses_c {
name BuildClasses.c
}
Target_BuildClasses_c-> File_BuildClasses_c
class Task_build_classes {
name build classes
description this c class is responsible of building other classes
}
Target_BuildClasses_c-up->Task_build_classes
class Property_build {
name build
value build
}
Task_build_classes->Property_build
class Target_BuildDependencies_c {
}
Project ->Target_BuildDependencies_c
class File_BuildDependencies_c {
name BuildDependencies.c
}
Target_BuildDependencies_c-> File_BuildDependencies_c
class Task_build_dependencies {
name build dependencies
description this class is responsible for the connecting the dependencies
}
Target_BuildDependencies_c->Task_build_dependencies
class Property_buildDep {
name buildDep
value buildDep
}
Task_build_dependencies->Property_buildDep
class Target_InfoBuilder_lib {
}
Project ->Target_InfoBuilder_lib
class File_InfoBuilder_lib {
name InfoBuilder.lib
}
Target_InfoBuilder_lib-> File_InfoBuilder_lib
class Task_InformationLibrary {
name InformationLibrary
description File contains a library of information used by a specific program. It may store a variety of information.
}
Target_InfoBuilder_lib->Task_InformationLibrary
class Property_lib {
name lib
value lib
}
Task_InformationLibrary->Property_lib
class Target_header_h {
}
Project ->Target_header_h
class File_header_h {
name header.h
}
Target_header_h-> File_header_h
class Task_DeclarationsToShare {
name DeclarationsToShare
description C function declarations and macro definitions to be shared between several source files.
}
Target_header_h->Task_DeclarationsToShare
class Property_dec {
name dec
value dec
}
Task_DeclarationsToShare->Property_dec
class Task_deleteFiles {
name deleteFiles
description task to delete the temporary files generated by the build
}
Project ->Task_deleteFiles
class Action_delete_jar_files{
name delete jar files
}
Task_deleteFiles -> Action_delete_jar_files
class InstructionBlock_delete_jar_files {
}
Action_delete_jar_files -> InstructionBlock_delete_jar_files
class Start_delete_jar_files {
}
Action_delete_jar_files -> Start_delete_jar_files
class End_delete_jar_files {
}
Action_delete_jar_files -> End_delete_jar_files
class Decision_delete_jar_files {
}
Action_delete_jar_files -> Decision_delete_jar_files
class Property_isTempFile {
name isTempFile
value boolean
}
Decision_delete_jar_files -> Property_isTempFile
@enduml
