/*
 * generated by Xtext 2.28.0
 */
package pt.isep.edom.xtext.assignment1;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
